In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.03375977, -0.18744135,  0.19177699,  0.64770347, -0.02015234,
         0.08704978, -0.34529752, -0.24626088,  0.78065944, -0.16614401]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.0840042 , 0.07203738, 0.10525686, 0.16605683, 0.08515509,
        0.09479118, 0.06151795, 0.06792239, 0.18967006, 0.07358804]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.3560789

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2970 - accuracy: 0.9142
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1432 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1078 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0889 - accuracy: 0.9725
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0769 - accuracy: 0.9757


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0725 - accuracy: 0.9785 - 1s/epoch - 4ms/step


[0.07254789024591446, 0.9785000085830688]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.90032368e-09, 3.87219634e-09, 9.35419848e-06, 2.48284014e-05,
        1.69413789e-11, 2.26634889e-08, 1.71517463e-14, 9.99963641e-01,
        3.92376705e-07, 1.92013226e-06],
       [6.91507429e-09, 5.76068669e-06, 9.99908566e-01, 8.34570819e-05,
        2.35162477e-15, 8.62029140e-07, 6.53965715e-10, 6.83324968e-12,
        1.32556829e-06, 2.09870844e-14],
       [1.06718371e-05, 9.97222304e-01, 6.30636001e-04, 5.50739933e-05,
        9.22180789e-06, 8.46220064e-05, 4.77430913e-05, 6.25808607e-04,
        1.31175737e-03, 2.13381986e-06],
       [9.98748899e-01, 2.10259768e-10, 1.11016014e-03, 5.89984893e-07,
        2.37361419e-07, 2.15561413e-05, 6.03184526e-05, 2.43211725e-05,
        5.23808978e-07, 3.34035249e-05],
       [1.53543951e-05, 5.99701566e-10, 1.00557963e-06, 1.48527315e-08,
        9.98484433e-01, 9.27052781e-08, 1.17014797e-05, 3.52425232e-05,
        5.74294631e-07, 1.45163108e-03]], dtype=float32)>